name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Determine image tag based on branch
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [ "$BRANCH" = "main" ]; then
            if [ -f VERSION ]; then
              VERSION=$(cat VERSION)
              echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV
              echo "Using version tag: $VERSION"
            else
              echo "VERSION file not found, using latest"
              echo "IMAGE_TAG=latest" >> $GITHUB_ENV
              echo "Using version tag: latest"
            fi
          else
            IMAGE_TAG=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]')
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
            echo "Using branch tag: $IMAGE_TAG"
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ env.REPO_OWNER_LC }}/web-fusee-launcher:${{ env.IMAGE_TAG }}
